<?php
/**
 * @file 
 * Stops page from changing when user is posting.
 */
function aps_pageexit_node_view($node, $view_mode, $langcode) {
	if ($node->type == 'page' && drupal_get_path_alias() == 'webcast') {
		drupal_add_js(drupal_get_path('module', 'aps_pageexit') . '/aps_pageexit.js');
		drupal_add_js(drupal_get_path('module', 'aps_pageexit') . '/js/date.js');

		$start = !empty($node->field_event_start_date[LANGUAGE_NONE][0]['value']) ? $node->field_event_start_date[LANGUAGE_NONE][0]['value'] : '';
		$end = !empty($node->field_event_end_date[LANGUAGE_NONE][0]['value']) ? $node->field_event_end_date[LANGUAGE_NONE][0]['value'] : '';

		drupal_add_js(array('page_exit' => array('start_time' => $start, 'end_time' => $end)), 'setting');
	}
}

/**
 * Implements hook_menu().
 */
function aps_pageexit_menu() {
	$items['aps_pageexit/timeout'] = array(
	    'title' => 'Execute Rule', 
	    'page callback' => 'aps_pageexit_timeout', 
	    'access arguments' => array('access content'), 
	  );
  return $items;
}

function aps_pageexit_timeout() {
	rules_invoke_event('aps_pageexit_stopwatch');
}