<?php
/**
 * @file
 * Front-end interfaces that use the Google Analytics API module.
 */

/**
 * Implements hook_block_info().
 */
function aps_registration_analytics_block_info() {
  $blocks['common_browser']['info'] = t('Browser');
  $blocks['geo_location']['info'] = t('Geographic Locations');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function aps_registration_analytics_block_view($delta = '') {
  switch ($delta) {
    case 'common_browser':
      $block['subject'] = t('Browsers Used');
      $block['content'] = aps_common_browser_build();
      return $block;
    case 'geo_location':
      $block['subject'] = t('Geographic Locations');
      $block['content'] = aps_geo_location_build();
      return $block;
  }
}

/**
 * Generates a block with the most common Browsers.
 */
function aps_common_browser_build() {
  if (!variable_get('google_analytics_reports_oauth_token', FALSE)) {
    return '<p>' . t('You must <a href="!url">authorize</a> Drupal to use your Analytics account before you can view reports.', array('!url' => url('admin/config/system/google-analytics-reports'))) . '</p>';
  }

  $params = array(
    'metrics' => array('ga:users'),
    'dimensions' => array('ga:browser'),
    'sort_metric' => array(),
    'filters' => '',
    'start_date' => date('Y-m-d', strtotime('1 Jan 2015')),
    'end_date' => date('Y-m-d', strtotime('today')),
  );

  $feed = google_analytics_api_report_data($params);
  if ($feed->error) {
    return '<p>' . _google_analytics_reports_error_message() . '</p>';
  }
  foreach ($feed->results->rows as $row) {
    $rows[] = $row['users'];
    $header[] = $row['browser'];
  }

  $settings['chart']['browsers'] = array(  
    'header' => $header,
    'rows' => array($rows),
    'columns' => array("Usage"),
    'chartType' => 'PieChart',
    'containerId' =>  'aps-common-browser',
    'options' => array( // Optionals.
      'curveType' => "function",
      'is3D' => TRUE,
      'forceIFrame' => FALSE,
      'width' => 420,
      'height' => 220,
      'backgroundColor' => 'transparent'
    ),
  );

  draw_chart($settings);

  return '<div id="aps-common-browser"></div>';
}

/**
 * Generates a block of the Geographic locations.
 */
function aps_geo_location_build() {
  if (!variable_get('google_analytics_reports_oauth_token', FALSE)) {
    return '<p>' . t('You must <a href="!url">authorize</a> Drupal to use your Analytics account before you can view reports.', array('!url' => url('admin/config/system/google-analytics-reports'))) . '</p>';
  }

  $params = array(
    'metrics' => array('ga:users'),
    'dimensions' => array('ga:country'),
    'sort_metric' => array(),
    'filters' => '',
    'start_date' => date('Y-m-d', strtotime('1 Jan 2015')),
    'end_date' => date('Y-m-d', strtotime('today')),
  );

  $feed = google_analytics_api_report_data($params);
  if ($feed->error) {
    return '<p>' . _google_analytics_reports_error_message() . '</p>';
  }
  foreach ($feed->results->rows as $row) {
    $rows[] = $row['users'];
    $header[] = $row['country'];
  }

  $settings['chart']['location'] = array(  
      'header' => $header,
      'rows' => array($rows),
      'columns' => array("Viewers"),
      'chartType' => 'GeoChart',
      'containerId' =>  'aps-geo-location',
      'options' => array( 
        'forceIFrame' => FALSE, 
        'width' => 400,
        'height' => 280,
      )   
    );

  draw_chart($settings);
  
  return '<div id="aps-geo-location"></div>';
}

/**
 * Preprocess function for views-view.tpl.php.
 */
function aps_registration_analytics_preprocess_views_view(&$variables) {
  if ($variables['view']->name === 'tracking' && $variables['view']->current_display == 'graph_tracking') {
    active_watcher_build_graph($variables['view']->result);
    $variables['rows'] = '<div id="aps-active-watcher"></div>';
  }
}

/**
 * Draws graph in view block
 */
function active_watcher_build_graph($result){
  $now = time();
  $upper = ($now - strtotime("midnight", $now));

  $opening = ($node = node_load(3)) ? $node->field_event_start_date[LANGUAGE_NONE][0]['value'] : 0;
  $lower = ($opening != 0) ? (strtotime($opening . "- 30 minutes") - strtotime("midnight", $now)) : 0;

  $header = hoursRange($lower, $upper, 60 * 5);

  $time_rows = array_fill_keys($header, 0);
  $keys = array_keys($time_rows);
  $rows = array_fill(0, count($time_rows), 0);

  // Check the data hasn't started in a negative value
  if ($lower < $upper && $upper < 86400 && $lower < 86400) {
    // Loop through each result from the view
    foreach ($result as $record) {
      // Loop through each value within each result
      for ($i=0; $i < count($record->field_field_start_watching) ; $i++) { 
        // Fetch the start/end time of the entry
        $start_time = strtotime($record->field_field_start_watching[$i]['raw']['value']);
        $end_time = !empty($record->field_field_end_watching) ? strtotime($record->field_field_end_watching[$i]['raw']['value']) : NULL;
        for ($j=0; $j < count($time_rows); $j++) { 
          $row_time = strtotime($keys[$j]);
          if ($start_time < $row_time) {
            $rows[$j]++;
          }
          if (!empty($end_time) && ($end_time < $row_time)) {
            $rows[$j]--;
          }
        }
      }
    }
  }
    
  $settings['chart']['viewers'] = array(
    'header' => $header,
    'rows' => array($rows),
    'columns' => array("Viewers"),
    'chartType' => 'SteppedAreaChart',
    'containerId' => 'aps-active-watcher',
    'options' => array(
      'forceIFrame' => FALSE,
      'width' => 420,
      'height' => 220,
      'backgroundColor' => 'transparent',
      ),
    );

  draw_chart($settings); 
}

/**
 * Creates a range of times in a specific formatting
 */
function hoursRange($lower = 0,$upper = 86400,$step = 3600,$format = '') {
    $times = array();
    if (empty($format)) {
      $format = 'g:i a';
    }

    foreach (range($lower, $upper, $step) as $increment) {
        $increment = gmdate('H:i', $increment);
        list($hour, $minutes) = explode(':', $increment);
        $date = new DateTime( $hour . ':' . $minutes);
        $times[] = $date->format($format);
    }

    return $times;
}

/*
 * Construct a filter string that only allows the hours the webcast is active.
 */
function _google_analytics_reports_live_filter($start = '', $end = '') {
  if (!empty($start) && !empty($end)) {
    foreach (range(date('H', strtotime($start)), date('H', strtotime($end))) as $hour) {
      $hours[] = 'ga:hour==' . str_pad($hour, 2, 0, STR_PAD_LEFT);
    }
    return implode(',',$hours);
  } 
}